packages:
  - src/ui/web

onlyBuiltDependencies:
  - '@compodoc/compodoc'
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - less
  - lmdb
  - msgpackr-extract
  - nx

overrides:
  axios@<1.15.0: '>=1.15.0'
