arrowParens: avoid
bracketSameLine: true
endOfLine: lf
jsxSingleQuote: true
printWidth: 150
semi: true
singleQuote: true
tabWidth: 4
trailingComma: none
useTabs: false

overrides:
  - files: "*.json"
    options:
      jsxSingleQuote: false
      singleQuote: false
      tabWidth: 2
