import type { Config } from 'tailwindcss';

const latte = {
  rosewater: '#dc8a78',
  flamingo: '#dd7878',
  pink: '#ea76cb',
  mauve: '#8839ef',
  red: '#d20f39',
  maroon: '#e64553',
  peach: '#fe640b',
  yellow: '#df8e1d',
  green: '#40a02b',
  teal: '#179299',
  sky: '#04a5e5',
  sapphire: '#209fb5',
  blue: '#1e66f5',
  lavender: '#7287fd',
  text: '#4c4f69',
  subtext1: '#5c5f77',
  subtext0: '#6c6f85',
  overlay2: '#7c7f93',
  overlay1: '#8c8fa1',
  overlay0: '#9ca0b0',
  surface2: '#acb0be',
  surface1: '#bcc0cc',
  surface0: '#ccd0da',
  base: '#eff1f5',
  mantle: '#e6e9ef',
  crust: '#dce0e8',
} as const;

const mocha = {
  rosewater: '#f5e0dc',
  flamingo: '#f2cdcd',
  pink: '#f5c2e7',
  mauve: '#cba6f7',
  red: '#f38ba8',
  maroon: '#eba0ac',
  peach: '#fab387',
  yellow: '#f9e2af',
  green: '#a6e3a1',
  teal: '#94e2d5',
  sky: '#89dceb',
  sapphire: '#74c7ec',
  blue: '#89b4fa',
  lavender: '#b4befe',
  text: '#cdd6f4',
  subtext1: '#bac2de',
  subtext0: '#a6adc8',
  overlay2: '#9399b2',
  overlay1: '#7f849c',
  overlay0: '#6c7086',
  surface2: '#585b70',
  surface1: '#45475a',
  surface0: '#313244',
  base: '#1e1e2e',
  mantle: '#181825',
  crust: '#11111b',
} as const;

const config: Config = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'mnl-latte': latte,
        'mnl-mocha': mocha,
        'mnl-bg': 'var(--mnl-color-bg)',
        'mnl-surface': 'var(--mnl-color-surface)',
        'mnl-surface-alt': 'var(--mnl-color-surface-alt)',
        'mnl-surface-muted': 'var(--mnl-color-surface-muted)',
        'mnl-border': 'var(--mnl-color-border)',
        'mnl-text': 'var(--mnl-color-text)',
        'mnl-subtext': 'var(--mnl-color-subtext)',
        'mnl-accent': 'var(--mnl-color-accent)',
        'mnl-accent-strong': 'var(--mnl-color-accent-strong)',
        'mnl-pink': 'var(--mnl-color-accent)',
        'mnl-success': 'var(--mnl-color-success)',
        'mnl-warning': 'var(--mnl-color-warning)',
        'mnl-error': 'var(--mnl-color-error)',
        'mnl-red': 'var(--mnl-color-error)',
        'mnl-info': 'var(--mnl-color-info)',
      },
      fontFamily: {
        sans: ['"Nunito Sans"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      boxShadow: {
        sm: '0 1px 2px 0 rgb(17 17 27 / 0.06), 0 1px 3px 0 rgb(17 17 27 / 0.10)',
        md: '0 12px 24px -12px rgb(17 17 27 / 0.25)',
      },
      borderRadius: {
        xl: '0.75rem',
        '2xl': '1rem',
      },
    },
  },
};

export default config;
