### Get Electricity Usage

GET {{ baseUrl }}/utilities/electricity?startDate=2024-07-11&endDate=2024-07-12&timeZone=Africa%2FJohannesburg HTTP/2
Authorization: Bearer {{$auth.token("Api")}}

### Capture Electricity Usage

POST {{ baseUrl }}/utilities/electricity/usage HTTP/2
Content-Type: application/json
Authorization: Bearer {{$auth.token("Api")}}

{
    "date": "2024-08-04",
    "units": "715.43",
    "applianceUsages": []
}

### Capture Electricity Purchase

POST {{ baseUrl }}/utilities/electricity/purchase HTTP/2
Content-Type: application/json
Authorization: Bearer {{$auth.token("Api")}}

{
    "date": "2024-08-01",
    "units": "675.00",
    "cost": "2500.00",
    "applianceUsages": []
}

### Capture Water Reading

POST {{ baseUrl }}/utilities/water/reading HTTP/2
Content-Type: application/json
Authorization: Bearer {{$auth.token("Api")}}

{
    "captureDate": "2024-08-02",
    "reading": 1600.000,
    "cost": {
        "ccy": "ZAR",
        "amount": 1209.00
    }
}

### Get Water Readings

GET {{ baseUrl }}/utilities/water/reading?startDate=2024-08-02&endDate=2024-08-02&timeZone=Africa%2FJohannesburg HTTP/2
Content-Type: application/json
Authorization: Bearer {{$auth.token("Api")}}
