# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test

    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: read
      checks: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src/Menlo.sln
    - name: Build
      run: dotnet build src/Menlo.sln --no-restore
    - name: Test
      run: dotnet test src/Menlo.sln --no-build --verbosity normal --logger trx
    - name: Test Report
      uses: dorny/test-reporter@v1
      with:
        name: Tests
        path: 'src/**/*.trx'
        reporter: dotnet-trx
