# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test

    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: read
      checks: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore local tools
      run: dotnet tool restore
    - name: Restore dependencies
      run: dotnet restore src/Menlo.sln
    - name: Build
      run: dotnet build src/Menlo.sln --no-restore
    - name: Test
      run: dotnet test src/Menlo.sln --no-build --verbosity normal --logger trx --collect:"XPlat Code Coverage"
    - name: Generate Test Report
      uses: dorny/test-reporter@v1
      with:
        name: Tests
        path: 'src/**/*.trx'
        reporter: dotnet-trx
    - name: Generate Coverage Report
      run: dotnet reportgenerator -reports:src/**/TestResults/**/coverage.cobertura.xml -targetdir:./coverage -reporttypes:MarkdownSummary
    - name: Coverage Check
      uses: LouisBrunner/checks-action@v2.0.0
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Code coverage
        conclusion: ${{ job.status }}
        output: '{"summary":"Code coverage"}'
        output_text_description_file: coverage/Summary.md
